### PR TITLE
Added creator to all info.txt files

### PR DESCRIPTION
**Pull request by backstander**
I put creator = "simbz23"
On the RetroPie forum your name is  "simbz23" but on GitHub it is "simbz33"

### CODE REVIEW

**Comment by simbz33** [comment]
Thanks for the heads up!

**Comment by simbz33** [comment]
@backstander And yes unfortunately simbz23 on github was taken :-(

**Comment by backstander** [comment]
That's odd.  I would have figured your name being unique enough that it wouldn't have be taken here.  I enjoy your overlays!

**Comment by simbz33** [comment]
@backstander Thanks brother, I really appreciate the love, glad everybody is enjoying as much I like making them!

**Pull request merged**
